### ISSUE TITLE
endless loop on windows if there is no spr repository

### ISSUE THREAD

**Issue by franzhaas** [abingham/spor#2]
Hi,

i assume this is the repo for this package... 
https://pypi.python.org/pypi/spor/1.0.0

I experience an endless loop on windows in the 

_find_root_dir

function

path, never becomes "root", I changed the function to.:

def _find_root_dir(path, spor_dir):
    """Search for a spor repo containing `path`.

    This searches for `spor_dir` in directories dominating `path`. If a
    directory containing `spor_dir` is found, then that directory is returned
    as a `pathlib.Path`.

    Returns: The dominating directory containing `spor_dir` as a
      `pathlib.Path`.

    Raises:
      ValueError: No repository is found.

    """
    path = pathlib.Path(os.getcwd() if path is None else path)

    while True:
        next_path = path.parent.resolve()
        data_dir = path / spor_dir
        if data_dir.exists() and data_dir.is_dir():
            return path

        if path == next_path:
            raise ValueError('No spor repository found')

        path = next_path

And it works for me... If this is the right development place for this package, i happily provide a pull request...

**Comment by abingham** [comment]
Yep, this is the right place. Thanks for reporting this; I (clearly!) don't test on windows.

On first glance your solution looks fine. Please do create a PR.

It's a bit frustrating that `pathlib` behaves this way. I don't see anything in the docs indicating that we should expect it, but maybe I'm not paying enough attention.

Thanks again.

**Comment by abingham** [comment]
Fixed by #3.
